<?xml version="1.0" encoding="utf-8"?><Database Name="student" Class="StudentClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-6JOEM91O\SQLEXPRESS01;Initial Catalog=student;Integrated Security=True" SettingsObjectName="LINQtoSql.Properties.Settings" SettingsPropertyName="studentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.stud_details" Member="stud_detail1s">
    <Type Name="stud_detail1">
      <Column Name="rno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>